builds:
- id: spin-plugin-azure
  main: ./
  binary: spin-azure
  env:
   - CGO_ENABLED=0
  ldflags:
   - "-s -w -X github.com/spinkube/spin-plugin-azure/pkg/cmd.Version={{.Version}}"
  goos:
   - linux
   - darwin
   - windows
  goarch:
   - amd64
   - arm64 

archives:
- builds:
  - id: spin-plugin-azure
    main: ./
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: false
    format: tar.gz
    files:
    - LICENSE
